permalink: /about.md
title: Y1xuan Zhang
logo: /assets/img/k.png
description: 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  is_user_page: true 
  is_project_page: false



